name: Demo Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print event information
        run: echo "Event name: ${{ github.event_name }}"
      
      - name: Print runner information
        run: echo "Running on: ${{ runner.os }}"
      
      - name: Print repository information
        run: |
          echo "Branch name: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Print clone message
        run: echo "Repository code cloned"
      
      - name: Prepare environment
        run: |
          ls ${{ github.workspace }}
          chmod +x ./gradlew
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      
      - name: Run tests
        run: ./gradlew test
      
      - name: Build project
        run: ./gradlew assemble
        
